#!/usr/bin/env bash

declare -r git_tag="$(git describe --tags --abbrev=0)"
declare -r head_count=$(git rev-list --count HEAD)
declare -r tag_count=$(git rev-list --count "${git_tag:?}")
declare -r count_diff=$((${head_count:?} - ${tag_count:?}))
declare release_version="${git_tag:?}"
declare tag_latest=false

[[ ${count_diff} -gt 0 || -n $(git status -s) ]] && release_version="sha-$(git rev-parse --short HEAD)-next"
[[ ${count_diff} -gt 0 ]] && release_version+="-${count_diff:?}"
[[ -n $(git status -s) ]] && release_version+="-dirty"
[[ "${release_version:?}" == "${git_tag:?}" ]] && tag_latest=true

export BASEOPS_VERSION='v1-alpha.1' # The base image version to use
export BASEOPS_CLI_PLATFORMS="linux/arm64,linux/amd64"
export BASEOPS_CLI_IMAGE="kristofferahl/baseops-cli"
export BASEOPS_CLI_VERSION="${release_version:?}"

if [[ ${BASEOPS_SIMPLE_RELEASE} == true ]]; then
  echo "Building image (local only)..."
  export DOCKER_BUILDKIT=1
  docker build --platform "linux/${BASEOPS_SIMPLE_ARCH:-arm64}" --build-arg "BASEOPS_CLI_IMAGE=${BASEOPS_CLI_IMAGE:?}" --build-arg="BASEOPS_CLI_VERSION=${BASEOPS_CLI_VERSION:?}" --build-arg "BASEOPS_VERSION=${BASEOPS_VERSION:?}" -t "${BASEOPS_CLI_IMAGE:?}:${BASEOPS_CLI_VERSION:?}" .
else
  echo
  echo "Releasing image ${BASEOPS_CLI_IMAGE:?}:${BASEOPS_CLI_VERSION:?}"
  echo -n "Continue? [y/N]: " && read -r OK
  grep -iq "^y" <<<"${OK:-}" || exit 1

  echo "Setting up buildx builder..."
  if ! docker buildx use mpb-baseops &>/dev/null; then
    docker buildx create --use --platform "${BASEOPS_CLI_PLATFORMS:?}" --name mpb-baseops
    docker buildx inspect --bootstrap
  fi

  echo
  echo "Building image ${BASEOPS_CLI_IMAGE:?}:${BASEOPS_CLI_VERSION:?}..."
  docker buildx build --push --platform "${BASEOPS_CLI_PLATFORMS:?}" --build-arg "BASEOPS_CLI_IMAGE=${BASEOPS_CLI_IMAGE:?}" --build-arg="BASEOPS_CLI_VERSION=${BASEOPS_CLI_VERSION:?}" --build-arg "BASEOPS_VERSION=${BASEOPS_VERSION:?}" -t "${BASEOPS_CLI_IMAGE:?}:${BASEOPS_CLI_VERSION:?}" .

  if [[ ${tag_latest:?} == true ]]; then
    docker tag "${BASEOPS_CLI_IMAGE:?}:${BASEOPS_CLI_VERSION:?}" "${BASEOPS_CLI_IMAGE:?}:latest"
    docker push "${BASEOPS_CLI_IMAGE:?}:latest"
  fi
fi
