#!/usr/bin/env bash

# shellcheck disable=SC1091
source ./release || exit 1

echo
echo "Running container ${BASEOPS_CLI_IMAGE:?}/${BASEOPS_CLI_VERSION:?} ... $*"
docker run --rm -it \
  -v "/${PWD:?}:/work" \
  -e "OUTPUT_DIR=/work/generated" \
  "${BASEOPS_CLI_IMAGE:?}:${BASEOPS_CLI_VERSION:?}" \
  "${@}"

echo "Exit code: $?"
