Output demo.gif

Set Shell bash
Set Width 1400
Set Height 600
Set FontSize 20

Type 'docker run --rm -it -v "/${PWD:?}:/work" kristofferahl/baseops-cli:latest init'
Sleep 500ms
Enter

Sleep 2s

Type "glam"
Sleep 2s
Enter

Sleep 2s
Enter

Type "orous"
Sleep 2s
Enter

Sleep 2s
Enter

Sleep 2s
Enter

Sleep 4s
Enter

Sleep 2s
Type "./glam baseops build"
Sleep 1s
Enter

Sleep 8s

Type "./glam shell"
Sleep 1s
Enter

Sleep 8s

Type "exit"
Sleep 1s
Enter

Sleep 2s
