#!/usr/bin/env bash

echo "Building docker image ${DOCKER_IMAGE:?}:${DOCKER_TAG:?} ..."

echo "Ensuring we are logged in with docker..."
docker login

echo "Setting up buildx builder..."
if ! docker buildx use mpb-baseops &>/dev/null; then
  docker buildx create --use --platform "${DOCKER_PLATFORMS:?}" --name mpb-baseops
  docker buildx inspect --bootstrap
fi

echo "Building and pushing image..."
export DOCKER_BUILDKIT=1
docker buildx build --push --platform "${DOCKER_PLATFORMS:?}" -t "${DOCKER_IMAGE:?}:${DOCKER_TAG:?}" --file .baseops/Dockerfile .baseops/
